/**
 * FDI-1.0 question set — FROZEN. Question set version FDI-QS-1.0.
 *
 * ⚠️  DO NOT EDIT THIS FILE. See config/fdi-1.0.ts for the versioning rule.
 *
 * §3 Question design standard: every item uses ITEM-SPECIFIC BEHAVIOURAL answers —
 * never agree/disagree, yes/no, or good/bad scales. Each follows: observable
 * situation → four behaviourally meaningful states → increasing dependency.
 *
 * §3 Scoring is uniform: 0 low dependency · 1 some dependency · 2 material
 * dependency · 3 strong dependency. No reverse scoring in v1.
 *
 * §17 Response-quality control: options are an ORDERED low-to-high dependency
 * scale and MUST stay logically sequenced. Do not randomise them. Randomisation
 * distributes order effects for nominal choices but is inappropriate for a
 * meaningful ordinal sequence.
 *
 * Option ids are opaque and stable (`DS1-A`..`DS1-D` = presentation position).
 * The score is carried on the option and is never derived from position, so a
 * future version could reorder or reverse-code without invalidating stored ids.
 */

import type { FdiQuestionSet } from '../types';

export const FDI_1_0_QUESTIONS: FdiQuestionSet = Object.freeze({
  questionSetVersion: 'FDI-QS-1.0',
  questions: Object.freeze([
    // ── §4 DECISION SPEED ────────────────────────────────────────────────────
    Object.freeze({
      id: 'DS1',
      componentKey: 'DS',
      text: 'When an important operating decision needs to be made and you are unavailable, what usually happens?',
      options: Object.freeze([
        Object.freeze({ id: 'DS1-A', score: 0, text: 'The responsible person makes the decision within defined authority' }),
        Object.freeze({ id: 'DS1-B', score: 1, text: 'Most decisions continue, but some still wait for me' }),
        Object.freeze({ id: 'DS1-C', score: 2, text: 'Many important decisions slow down until I am available' }),
        Object.freeze({ id: 'DS1-D', score: 3, text: 'Important decisions usually stop until I decide' }),
      ]),
    }),
    Object.freeze({
      id: 'DS2',
      componentKey: 'DS',
      text: 'How much authority does your team have to make recurring operating decisions without your approval?',
      options: Object.freeze([
        Object.freeze({ id: 'DS2-A', score: 0, text: 'Decision rights are clear and recurring decisions are handled without me' }),
        Object.freeze({ id: 'DS2-B', score: 1, text: 'Most routine decisions are handled without me, with some unnecessary escalation' }),
        Object.freeze({ id: 'DS2-C', score: 2, text: 'The team handles smaller decisions, but many operating decisions still require my approval' }),
        Object.freeze({ id: 'DS2-D', score: 3, text: 'I approve most meaningful operating decisions' }),
      ]),
    }),
    Object.freeze({
      id: 'DS3',
      componentKey: 'DS',
      text: 'When work is waiting for a decision that requires you, how long does it typically wait?',
      auditNote: 'Audit verifies with actual cycle-time samples.',
      options: Object.freeze([
        Object.freeze({ id: 'DS3-A', score: 0, text: 'It rarely waits for me because the responsible person can decide' }),
        Object.freeze({ id: 'DS3-B', score: 1, text: 'Usually no more than a few hours' }),
        Object.freeze({ id: 'DS3-C', score: 2, text: 'Often until later that day or the next working day' }),
        Object.freeze({ id: 'DS3-D', score: 3, text: 'It regularly waits more than one working day or remains blocked' }),
      ]),
    }),
    Object.freeze({
      id: 'DS4',
      componentKey: 'DS',
      text: 'How often are you pulled into operating decisions that someone else should reasonably be able to make?',
      options: Object.freeze([
        Object.freeze({ id: 'DS4-A', score: 0, text: 'Rarely' }),
        Object.freeze({ id: 'DS4-B', score: 1, text: 'Occasionally' }),
        Object.freeze({ id: 'DS4-C', score: 2, text: 'Frequently' }),
        Object.freeze({ id: 'DS4-D', score: 3, text: 'Daily or almost continuously' }),
      ]),
    }),

    // ── §5 EXECUTION CONSISTENCY ─────────────────────────────────────────────
    Object.freeze({
      id: 'EC1',
      componentKey: 'EC',
      text: 'For important work that happens repeatedly, how much of the correct way to perform it is documented and usable by the team?',
      options: Object.freeze([
        Object.freeze({ id: 'EC1-A', score: 0, text: 'Critical repeated work is documented, accessible, and actively used' }),
        Object.freeze({ id: 'EC1-B', score: 1, text: 'Most critical work is documented, with some gaps' }),
        Object.freeze({ id: 'EC1-C', score: 2, text: 'Some documentation exists, but much still depends on individual knowledge' }),
        Object.freeze({ id: 'EC1-D', score: 3, text: "Most important work lives in people's heads, especially mine or a few key employees" }),
      ]),
    }),
    Object.freeze({
      id: 'EC2',
      componentKey: 'EC',
      text: 'When different capable team members perform the same recurring work, how consistent is the final result?',
      options: Object.freeze([
        Object.freeze({ id: 'EC2-A', score: 0, text: 'The result consistently meets the same defined standard' }),
        Object.freeze({ id: 'EC2-B', score: 1, text: 'Results are usually consistent, with occasional differences' }),
        Object.freeze({ id: 'EC2-C', score: 2, text: 'Quality varies noticeably depending on who performs the work' }),
        Object.freeze({ id: 'EC2-D', score: 3, text: 'Reliable quality depends heavily on particular people or my involvement' }),
      ]),
    }),
    Object.freeze({
      id: 'EC3',
      componentKey: 'EC',
      text: 'How often does completed work need correction, re-explanation, or rework because the expected standard was not followed?',
      options: Object.freeze([
        Object.freeze({ id: 'EC3-A', score: 0, text: 'Rarely' }),
        Object.freeze({ id: 'EC3-B', score: 1, text: 'Occasionally' }),
        Object.freeze({ id: 'EC3-C', score: 2, text: 'Frequently' }),
        Object.freeze({ id: 'EC3-D', score: 3, text: 'Rework and correction are a normal part of operations' }),
      ]),
    }),
    Object.freeze({
      id: 'EC4',
      componentKey: 'EC',
      text: 'When you are not personally supervising day-to-day execution, what usually happens to delivery quality or speed?',
      options: Object.freeze([
        Object.freeze({ id: 'EC4-A', score: 0, text: 'Standards remain substantially unchanged' }),
        Object.freeze({ id: 'EC4-B', score: 1, text: 'Some issues appear, but the team generally maintains normal delivery' }),
        Object.freeze({ id: 'EC4-C', score: 2, text: 'Quality or speed noticeably deteriorates' }),
        Object.freeze({ id: 'EC4-D', score: 3, text: 'Significant disruption or quality problems occur or are expected' }),
      ]),
    }),

    // ── §6 OPERATIONAL VISIBILITY ────────────────────────────────────────────
    Object.freeze({
      id: 'OV1',
      componentKey: 'OV',
      text: 'Can you see the current status of important business activities without asking individual team members for updates?',
      options: Object.freeze([
        Object.freeze({ id: 'OV1-A', score: 0, text: 'Yes — important status is visible through current reports or dashboards' }),
        Object.freeze({ id: 'OV1-B', score: 1, text: 'Mostly — I occasionally need clarification' }),
        Object.freeze({ id: 'OV1-C', score: 2, text: 'Only partly — I regularly need to ask people for updates' }),
        Object.freeze({ id: 'OV1-D', score: 3, text: 'No — asking people is the main way I find out what is happening' }),
      ]),
    }),
    Object.freeze({
      id: 'OV2',
      componentKey: 'OV',
      text: 'How current is the information you rely on to understand operational performance?',
      options: Object.freeze([
        Object.freeze({ id: 'OV2-A', score: 0, text: 'Updated at the frequency needed to manage the business' }),
        Object.freeze({ id: 'OV2-B', score: 1, text: 'Usually current, with occasional delays' }),
        Object.freeze({ id: 'OV2-C', score: 2, text: 'Often outdated when I receive it' }),
        Object.freeze({ id: 'OV2-D', score: 3, text: 'I regularly lack reliable current information' }),
      ]),
    }),
    Object.freeze({
      id: 'OV3',
      componentKey: 'OV',
      text: 'How do you usually discover an important operational problem?',
      options: Object.freeze([
        Object.freeze({ id: 'OV3-A', score: 0, text: 'Our reporting or management system identifies it early' }),
        Object.freeze({ id: 'OV3-B', score: 1, text: 'The team identifies and reports it through an established process' }),
        Object.freeze({ id: 'OV3-C', score: 2, text: 'Someone normally tells me after it has already affected work' }),
        Object.freeze({ id: 'OV3-D', score: 3, text: 'I often discover it myself, through a customer, or after it becomes urgent' }),
      ]),
    }),
    Object.freeze({
      id: 'OV4',
      componentKey: 'OV',
      text: 'How often do you personally have to chase employees for status, progress, numbers, or explanations?',
      options: Object.freeze([
        Object.freeze({ id: 'OV4-A', score: 0, text: 'Rarely — the information is normally available when needed' }),
        Object.freeze({ id: 'OV4-B', score: 1, text: 'Occasionally' }),
        Object.freeze({ id: 'OV4-C', score: 2, text: 'Frequently' }),
        Object.freeze({ id: 'OV4-D', score: 3, text: 'Chasing updates is a regular part of my day' }),
      ]),
    }),
  ]),
} satisfies FdiQuestionSet);
