// Compiles the design system's stylesheet for the design-sync bundle.
//
// Why this exists: Tailwind v4 has no config file — the theme IS the @theme
// block in src/app/globals.css, and utilities are generated by scanning source.
// The app gets that compile from Next's PostCSS pipeline, which the DS bundle
// has no access to, so we run the same Tailwind version over the same input.
//
// It also binds --font-figtree / --font-roboto-slab. In the app those come from
// next/font/google at runtime; nothing injects them in the bundle, and an
// undefined custom property invalidates the whole font-family declaration, so
// without these bindings every component falls back to a system font.
//
// Run: node .design-sync/build-css.mjs   (wired as cfg.buildCmd)
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const CACHE = join(HERE, '.cache');
const CLI = join(ROOT, '.ds-sync/node_modules/@tailwindcss/cli/dist/index.mjs');
const IN = join(ROOT, 'src/app/globals.css');
const RAW = join(CACHE, 'tw-compiled.css');
const OUT = join(CACHE, 'ds-styles.css');

mkdirSync(CACHE, { recursive: true });
execFileSync(process.execPath, [CLI, '-i', IN, '-o', RAW], { stdio: 'inherit', cwd: ROOT });

const compiled = readFileSync(RAW, 'utf8');
const shim = `
/* ── design-sync additions (see .design-sync/build-css.mjs) ───────────────── */
/* next/font/google defines these on <html> in layout.tsx; the bundle has no
   next/font, and @theme's --font-body/--font-heading dereference them. */
:root {
  --font-figtree: "Figtree";
  --font-roboto-slab: "Roboto Slab";
}
/* layout.tsx applies these to <body> via "bg-canvas text-ink font-body".
   Reproduced so previews and generated designs inherit the same defaults the
   real site does. The app-shell layout classes (min-h-full flex flex-col) are
   deliberately NOT carried over — they belong to the page, not the DS. */
body {
  font-family: var(--font-body);
  background-color: var(--color-canvas);
  color: var(--color-ink);
}
`;
writeFileSync(OUT, compiled + shim);
console.error(`css: ${(compiled.length / 1024).toFixed(1)}KB compiled + font bindings → .design-sync/.cache/ds-styles.css`);
