// Downloads the exact Google Fonts faces src/app/layout.tsx loads via
// next/font/google, so the design-system bundle self-hosts them instead of
// depending on a font CDN at render time. Weights/subsets mirror layout.tsx —
// keep them in sync if that file changes.
// Run: node .design-sync/fetch-fonts.mjs
import { mkdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, 'fonts');
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';
const URL_ = 'https://fonts.googleapis.com/css2?family=Figtree:wght@300;400;500;600;700&family=Roboto+Slab:wght@500;600;700;800&display=swap';

const css = await (await fetch(URL_, { headers: { 'User-Agent': UA } })).text();
mkdirSync(OUT, { recursive: true });

// Google returns one @font-face per (family, weight, subset), each preceded by
// a /* <subset> */ comment. layout.tsx requests subsets:["latin"] only.
const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)];
const rules = [];
let n = 0;
for (const [, subset, rule] of blocks) {
  if (subset !== 'latin') continue;
  const fam = /font-family:\s*['"]([^'"]+)['"]/.exec(rule)?.[1] ?? 'font';
  const wght = /font-weight:\s*(\d+)/.exec(rule)?.[1] ?? '400';
  const url = /url\((https:[^)]+\.woff2)\)/.exec(rule)?.[1];
  if (!url) continue;
  const file = `${fam.toLowerCase().replace(/\s+/g, '-')}-${wght}.woff2`;
  const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
  writeFileSync(join(OUT, file), buf);
  rules.push(rule.replace(/url\(https:[^)]+\.woff2\)/, `url(./${file})`));
  n++;
  console.error(`  ${file}  ${(buf.length / 1024).toFixed(1)}KB`);
}
writeFileSync(join(OUT, 'fonts-src.css'),
  `/* Generated by .design-sync/fetch-fonts.mjs — @font-face only.\n   The --font-figtree / --font-roboto-slab bindings live in build-css.mjs,\n   because design-sync's extractFonts keeps @font-face rules and drops the rest. */\n`
  + rules.join('\n') + '\n');
console.error(`fonts: ${n} faces → .design-sync/fonts/`);
