/**
 * FDI-1.0 configuration — FROZEN.
 *
 * ⚠️  DO NOT EDIT THIS FILE.
 *
 * §18: "Historical sessions stay attached to the version used when completed... Never
 * silently recalculate FDI-1.0 under later rules." Any change to the instrument —
 * weights, bands, thresholds, item count, item range — requires a NEW version file
 * (fdi-1.1.ts) registered alongside this one, never an edit here.
 *
 * `config.lock.test.ts` hashes this object against a committed digest, so an edit
 * fails CI rather than silently re-scoring history.
 *
 * Owner-pinned decisions recorded here (previously open questions G, H, I, L):
 *   G — bandInput / alertInput both read the UNROUNDED value.
 *   H — display rounding is half-up.
 *   I — bands are half-open lower bounds: [0,25) [25,50) [50,75) [75,100].
 *   L — all components at or above the threshold are surfaced, ordered by score
 *       descending, ties grouped together with no further ordering.
 */

import type { FdiConfig } from '../types';

export const FDI_1_0_CONFIG: FdiConfig = Object.freeze({
  instrument: 'FDI',

  // §18 — the four version keys. The client submits `diagnosticVersion` only
  // (owner-pinned answer K); the other three are derived server-side from this
  // resolved config and stamped on the session row.
  diagnosticVersion: 'FDI-1.0',
  questionSetVersion: 'FDI-QS-1.0',
  scoringModelVersion: 'FDI-SM-1.0',
  bandConfigVersion: 'FDI-BC-1.0',

  // §2 — three components. This array's length is the "3"; the composite divisor
  // is the sum of `weights`, never a literal.
  components: Object.freeze([
    Object.freeze({ key: 'DS', label: 'Decision Speed' }),
    Object.freeze({ key: 'EC', label: 'Execution Consistency' }),
    Object.freeze({ key: 'OV', label: 'Operational Visibility' }),
  ]),

  // §1/§3 — 12 questions, four per component, each scored 0–3.
  // rawMax is derived (itemsPerComponent * itemScoreMax = 12) and never written.
  itemsPerComponent: 4,
  itemScoreMin: 0,
  itemScoreMax: 3,

  // §7 — Component Score = (Raw / rawMax) * componentScale.
  componentScale: 100,

  // §8 — equal weighting for v1. Implemented as configuration, never scattered
  // constants. FDI = Σ(wᵢ·Cᵢ) / Σwᵢ, which at equal weights is exactly (DS+EC+OV)/3.
  weights: Object.freeze({ DS: 1, EC: 1, OV: 1 }),

  // §10 — severe component alert. Provisional and configurable; not a validated
  // risk threshold.
  componentAlertThreshold: 75,

  // §9 — provisional v1 operating bands. NOT industry benchmarks, population
  // percentiles, validated cutoffs, or claims about business performance.
  // Band names must never read as praise.
  bands: Object.freeze([
    Object.freeze({
      key: 'low',
      label: 'Low Founder Dependency',
      minInclusive: 0,
      displayRange: '0–24',
    }),
    Object.freeze({
      key: 'moderate',
      label: 'Moderate Founder Dependency',
      minInclusive: 25,
      displayRange: '25–49',
    }),
    Object.freeze({
      key: 'high',
      label: 'High Founder Dependency',
      minInclusive: 50,
      displayRange: '50–74',
    }),
    Object.freeze({
      key: 'very_high',
      label: 'Very High Founder Dependency',
      minInclusive: 75,
      displayRange: '75–100',
    }),
  ]),

  bandInput: 'unrounded',
  alertInput: 'unrounded',
  rounding: 'half-up',

  // §9 — "Present as: Founder Dependency Index: 67 / 100 — High Founder Dependency".
  // Never "67% dependent": that misrepresents an index score as an empirical
  // percentage. There is no '%' in this template and a test enforces its absence.
  presentationTemplate: 'Founder Dependency Index: {display} / {scaleMax} — {bandLabel}',

  // §14 — fixed limitation copy. Shipped with every report.
  limitationCopy:
    'This result is based on founder self-report. It identifies where dependency appears. ' +
    'It does not prove why it exists, the operational root cause, the single binding ' +
    'constraint, or what intervention will fix it.',

  // §14 — the only next step the free diagnostic offers.
  nextStep: Object.freeze({ label: 'Audit', href: '/contact' }),
} satisfies FdiConfig);
